import pyttsx3
print('Hi there, I am Storyteller today I will tell you a story...')
#Intro
friend=pyttsx3.init()
friend.say("Hi there, I am Storyteller. today I will tell you a story.")
friend.runAndWait()
#Title
print('Bad Habbits')
friend.say("Bad Habbits.")
friend.runAndWait()
#Story
print('Once upon a time there lived a Rich Buisnessman..')
friend.say("Once upon a time there lived a Rich Buisnessman")
friend.runAndWait()
print('The buisnessman had a boy named Sam.')
friend.say("The buisnessman had a boy. named Sam")
friend.runAndWait()
print('The boy was very clever and good at his studies. But he had some Bad Habbits too..')
friend.say("The boy was very clever and good at his studies. But he had some Bad Habbits too")
friend.runAndWait()
print('The buisnessman was very worried with his son.')
friend.say("The buisnessman was very worried with his son.")
friend.runAndWait()
print('He got an idea he took Sam to "The Wise Master"')
friend.say("He got an idea he took Sam to The Wise Master")
friend.runAndWait()
print('The buisnessman told everything to the "Wise Master" about Sam..')
friend.say("The buisnessman told everything to the Wise Master about Sam")
friend.runAndWait()
print('The "Wise Master" Called Sam.....Sam!!!!')
friend.say("The Wise Master Called Sam.....Sam!!!!.Sam quickly ran to Wise Master")
friend.runAndWait()
print('He said to Sam, Can you pluck this sapling for me please?')
friend.say("He said to Sam. Can you pluck this sapling for me please. sam quickly plucked the sapling with out any efforts.")
friend.runAndWait()
print('He again said, Can you pull this little tree for me please?')
friend.say("He again said, Can you pull this little tree for me please. sam pulled the small tree with some efforts.")
friend.runAndWait()
print('He again said, Can you pull this Tree for me please?')
friend.say("He again said, Can you pull this Tree for me please. It was a small tree often but sam pulled it with efforts.")
friend.runAndWait()
print('Thanks Sam, Can you do last one thing for me, Please pull that big Banyan Tree for me..')
friend.say("Thanks Sam. Can you do last one thing for me. Please pull that big Banyan Tree for me. Sam gone infront of that tree he tried and tried but it could not move from its place.")
friend.runAndWait()
print('Sorry Wise Master I could not remove that Banyan Tree for you')
friend.say("Sorry Wise Master I could not remove that Banyan Tree for you")
friend.runAndWait()
print('The big tree that you could not remove are your old Bad Habbits, Old Bad Habbits Could not be removed Easiy.')
friend.say("The big tree that you could not remove are your old Bad Habbits. Old Bad Habbits Could not be removed Easiy.")
friend.runAndWait()
print('Small sapling can be removed easily, Just like Small Bad Habbits..')
friend.say("Small sapling can be removed easily. Just like Small Bad Habbits")
friend.runAndWait()
print('So')
friend.say("So")
friend.runAndWait()
print('Did you')
friend.say("Did you")
friend.runAndWait()
print('Understand')
friend.say("Understand")
friend.runAndWait()
print('-----------------------------------')
print('            Storyteller            ')
print('         Made By Ravanger101       ')
print('-----------------------------------')
